In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Dataset/processed_data.csv')
df

,MWG,NWG,KWG,MDIMC,NDIMC,MDIMA,NDIMB,KWI,VWM,VWN,STRM,STRN,SA,SB,Run_time
0,16,16,16,8,8,8,8,2,1,1,0,0,0,0,116.3700
1,16,16,16,8,8,8,8,2,1,1,0,0,0,1,78.7050
2,16,16,16,8,8,8,8,2,1,1,0,0,1,0,80.5650
3,16,16,16,8,8,8,8,2,1,1,0,0,1,1,86.6375
4,16,16,16,8,8,8,8,2,1,1,0,1,0,0,118.6625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,128,128,32,32,32,32,32,8,4,4,1,0,1,1,17.8175
241596,128,128,32,32,32,32,32,8,4,4,1,1,0,0,36.0350
241597,128,128,32,32,32,32,32,8,4,4,1,1,0,1,35.1600
241598,128,128,32,32,32,32,32,8,4,4,1,1,1,0,28.4525
241599,128,128,32,32,32,32,32,8,4,4,1,1,1,1,17.8175

In [4]:
X = df.drop("Run_time", axis=1)
y = df["Run_time"]

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
#Liner Regression
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

#evaluate the model (intercept and slope)
print(regressor.intercept_) # b0
print(regressor.coef_) # b1 (Slope)

218.03680917580712
[ 1.41928158e+02  1.30532663e+02  4.08584083e+01 -1.31690457e+02
 -1.29009277e+02  9.72736079e+00  9.71461930e+00  1.16826670e+01
 -2.58960351e+00 -5.79932076e+00 -4.63121675e+00  1.19466456e-01
  1.97106306e+01  2.37025025e+01]

In [8]:
y_pred = regressor.predict(X_test)

df_sample = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df1 = df_sample.head(10)
df1

          Actual   Predicted
147294  100.4525  238.254309
208656  251.1800  228.592896
54062    66.1575  -77.894854
151429  235.9250  392.555653
107244   35.9875   53.001772
159883   40.5950  348.446790
4082     56.5425  -57.331813
193346   45.8850  271.700656
93834    27.5400   96.089106
143707   53.9225  226.577632

In [9]:
from sklearn import metrics
print('Mean Squared Error:{:.2f}'.format(metrics.mean_squared_error(y_test, y_pred)))

Mean Squared Error:80158.21

In [10]:
print('Linear Regression Model:')
print("Test Score {:.2f}".format(regressor.score(X_test, y_test)))

Linear Regression Model:
Test Score 0.40